All passing

diff --git a/.github/workflows/r_build.yaml b/.github/workflows/r_build.yaml
--- a/.github/workflows/r_build.yaml
+++ b/.github/workflows/r_build.yaml
@@ -38,18 +38,6 @@ jobs:
           extra-packages: any::rcmdcheck
           needs: check
 
-      - run: R CMD INSTALL .
-
-      - run: sh -c "R CMD build --keep-empty-dirs --no-resave-data . 2>&1 > /tmp/build.log || true && while grep -q 'not found' /tmp/build.log; do cat /tmp/build.log && Rscript -e 'tinytex::parse_install(\"/tmp/build.log\")' && R CMD build --keep-empty-dirs --no-resave-data . 2>&1 > /tmp/build.log || true; done"
-        continue-on-error: true
-
-      - run: cat /tmp/build.log
-        continue-on-error: true
-
-
-      - uses: r-lib/actions/check-r-package@v2
-        continue-on-error: true
-
       - run: echo ::set-output name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
         shell: bash
         id: repo
@@ -59,16 +47,60 @@ jobs:
         shell: bash
         id: pkg
 
-      - if: runner.os == 'macOS'
-        run: git clone https://github.com/Bioconductor/BBS && mkdir ${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir && cd BBS/utils && gcc chown-rootadmin.c -o chown-rootadmin && sudo chown root:admin chown-rootadmin && sudo chmod 4750 chown-rootadmin && cd ../../ && bash BBS/utils/build-universal.sh ${{ steps.repo.outputs.REPOSITORY_NAME }}_${{ steps.pkg.outputs.PKG_VERSION }}.tar.gz /Library/Frameworks/R.framework/Resources/bin/R ${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir
+      - run: |
+          echo ::set-output name=BUILT::$(echo "${{ steps.repo.outputs.REPOSITORY_NAME }}_${{ steps.pkg.outputs.PKG_VERSION }}")
+        shell: bash
+        id: builtfile
+
+      - if: runner.os == 'windows'
+        run: R.exe CMD INSTALL .
+        continue-on-error: true
+
+      - if: runner.os != 'windows'
+        run: R CMD INSTALL .
+        continue-on-error: true
+
+      - run: sh -c "R CMD build --keep-empty-dirs --no-resave-data . 2>&1 > /tmp/build.log || true && while grep -q 'not found' /tmp/build.log; do cat /tmp/build.log && Rscript -e 'tinytex::parse_install(\"/tmp/build.log\")' && R CMD build --keep-empty-dirs --no-resave-data . 2>&1 > /tmp/build.log || true; done"
+        continue-on-error: true
+
+      - run: cat /tmp/build.log
+        continue-on-error: true
 
       - if: runner.os == 'macOS'
-        run: R CMD INSTALL --preclean --no-multiarch --library=${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir ${{ steps.repo.outputs.REPOSITORY_NAME }}_${{ steps.pkg.outputs.PKG_VERSION }}.tar.gz
+        run: git clone https://github.com/Bioconductor/BBS && mkdir ${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir && cd BBS/utils && gcc chown-rootadmin.c -o chown-rootadmin && sudo chown root:admin chown-rootadmin && sudo chmod 4750 chown-rootadmin && cd ../../ && bash BBS/utils/build-universal.sh ${{ steps.builtfile.outputs.BUILT }}.tar.gz /Library/Frameworks/R.framework/Resources/bin/R ${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir
 
-      - run: mkdir -p /tmp/${{ matrix.config.os }} && cp ${{ steps.repo.outputs.REPOSITORY_NAME }}_${{ steps.pkg.outputs.PKG_VERSION }}.tar.gz /tmp/${{ matrix.config.os }}/${{ matrix.config.os }}-${{ steps.repo.outputs.REPOSITORY_NAME }}_${{ steps.pkg.outputs.PKG_VERSION }}.tar.gz
+      - if: runner.os == 'macOS'
+        run: R CMD INSTALL --preclean --no-multiarch --library=${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir ${{ steps.builtfile.outputs.BUILT }}.tar.gz
 
-      - uses: actions/upload-artifact@v3
+
+      - if: runner.os == 'windows'
+        run: R.exe CMD build --keep-empty-dirs --no-resave-data .
+
+      - if: runner.os == 'windows'
+        run: mkdir ${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir && R.exe CMD INSTALL --merge-multiarch --build --library=${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir ${{ steps.builtfile.outputs.BUILT }}.tar.gz && R.exe CMD INSTALL ${{ steps.builtfile.outputs.BUILT }}.zip && rm ${{ steps.builtfile.outputs.BUILT }}.zip
+
+      - if: runner.os == 'windows'
+        run: R.exe CMD INSTALL --merge-multiarch --build --library=${{ steps.repo.outputs.REPOSITORY_NAME }}.buildbin-libdir ${{ steps.builtfile.outputs.BUILT }}.tar.gz
+
+      - if: runner.os != 'windows'
+        run: mkdir -p /tmp/${{ matrix.config.os }} && cp ${{ steps.builtfile.outputs.BUILT }}.tar.gz /tmp/${{ matrix.config.os }}/${{ matrix.config.os }}-${{ steps.builtfile.outputs.BUILT }}.tar.gz
+
+      - if: runner.os == 'windows'
+        run: mkdir -p /tmp/${{ matrix.config.os }} && cp ${{ steps.builtfile.outputs.BUILT }}.zip /tmp/${{ matrix.config.os }}/${{ matrix.config.os }}-${{ steps.builtfile.outputs.BUILT }}.zip
+
+
+      - uses: r-lib/actions/check-r-package@v2
+        continue-on-error: true
+
+      - if: runner.os != 'windows'
+        uses: actions/upload-artifact@v3
         with:
-          name: "${{ matrix.config.os }}-${{ steps.repo.outputs.REPOSITORY_NAME }}_${{ steps.pkg.outputs.PKG_VERSION }}.tar.gz"
-          path: "/tmp/${{ matrix.config.os }}/${{ matrix.config.os }}-${{ steps.repo.outputs.REPOSITORY_NAME }}_${{ steps.pkg.outputs.PKG_VERSION }}.tar.gz"
+          name: "${{ matrix.config.os }}-${{ steps.builtfile.outputs.BUILT }}.tar.gz"
+          path: "/tmp/${{ matrix.config.os }}/${{ matrix.config.os }}-${{ steps.builtfile.outputs.BUILT }}.tar.gz"
+
+      - if: runner.os == 'windows'
+        uses: actions/upload-artifact@v3
+        with:
+          name: "${{ matrix.config.os }}-${{ steps.builtfile.outputs.BUILT }}.zip"
+          path: "/tmp/${{ matrix.config.os }}/${{ matrix.config.os }}-${{ steps.builtfile.outputs.BUILT }}.zip"
 
